name: Testing IoT-Dashboard setup

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Building Docker setup 
        run: |
          cp ci_env .env
          docker-compose pull
          docker-compose build
