##############################################################################
#
# Name: docker-compose.yml
#
# Function:
# 	Configure the docker-iot-dashboard collection of docker containers.
#
# Copyright:
#	This file copyright (c) 2017-2021 by
#
#		MCCI Corporation
#		3520 Krums Corners Road
#		Ithaca, NY 14850
#
#	Distributed under the terms of the license file shipped with this
#	collection.
#
# Authors:
#	Terry Moore, MCCI Corporation
#	Murugan Chandrasekar, MCCI Corporation
#	Based on work by Johan Stocking, The Things Network
#
##############################################################################

version: '3.8'
services:
 
   chirpstack-network-server:
    restart: unless-stopped
    image: chirpstack/chirpstack-network-server:3
    hostname: "chirpstack-network-server"
    volumes:
      - "${IOT_DASHBOARD_DATA}chirpstack/configuration/chirpstack-network-server:/etc/chirpstack-network-server"
    depends_on:
      - postgresql
      - mqtts
    links:
      - mqtts

  chirpstack-application-server:
    restart: unless-stopped
    image: chirpstack/chirpstack-application-server:3
    ports:
      - 8080:8080
    hostname: "chirpstack-application-server"
    volumes:
      - "${IOT_DASHBOARD_DATA}chirpstack/configuration/chirpstack-application-server:/etc/chirpstack-application-server"
    depends_on:
      - chirpstack-network-server

  chirpstack-gateway-bridge:
    restart: unless-stopped
    image: chirpstack/chirpstack-gateway-bridge:3
    ports:
      - 1700:1700/udp
    hostname: "chirpstack-gateway-bridge"
    volumes:
      - "${IOT_DASHBOARD_DATA}chirpstack/configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge"
    depends_on:
      - mqtts
      - postgresql
    links:
      - mqtts

  chirpstack-geolocation-server:
    image: chirpstack/chirpstack-geolocation-server:3
    volumes:
      - "${IOT_DASHBOARD_DATA}chirpstack/configuration/chirpstack-geolocation-server:/etc/chirpstack-geolocation-server"
    restart: unless-stopped

  postgresql:
    restart: unless-stopped
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - "${IOT_DASHBOARD_DATA}chirpstack/configuration/postgresql/initdb:/docker-entrypoint-initdb.d"
      - "${IOT_DASHBOARD_DATA}postgresqldata:/var/lib/postgresql/data"

  redis:
    restart: unless-stopped
    image: redis:5-alpine
    volumes:
      - "${IOT_DASHBOARD_DATA}redisdata:/data"

  mqtts:
    restart: unless-stopped
    build:
      context: ./mqtts
      dockerfile: Dockerfile
    ports:
      - "${IOT_DASHBOARD_PORT_MQTT_TCP:-1883}:1883"   #-----> Connection on this TCP port is insecure. can be added if needed
    volumes:
      - "${IOT_DASHBOARD_DATA}mqtt/credentials:/etc/mosquitto/credentials"
    ports:
      - 1883:1883
  
 
### end of file ###
